
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Download, Sparkles } from "lucide-react";
import { generateAnalysisPDF } from "@/utils/pdfGenerator";
import { useToast } from "@/components/ui/use-toast";

interface AIAnalysisCardProps {
  symbol: string;
  analysisResult: string;
  isLoading: boolean;
  onAnalyze: () => void;
}

export function AIAnalysisCard({ 
  symbol, 
  analysisResult, 
  isLoading, 
  onAnalyze 
}: AIAnalysisCardProps) {
  const { toast } = useToast();

  const handleDownload = () => {
    try {
      const pdf = generateAnalysisPDF(symbol, analysisResult);
      pdf.save(`${symbol}_analysis.pdf`);
      
      toast({
        title: "Success",
        description: "Analysis report downloaded successfully",
      });
    } catch (error) {
      console.error("Error generating PDF:", error);
      toast({
        title: "Error",
        description: "Failed to generate PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  const formatAnalysisText = (text: string) => {
    return text.split('**').map((part, index) => 
      index % 2 === 1 ? <strong key={index} className="font-bold">{part}</strong> : part
    );
  };

  return (
    <div className="flex flex-col items-center w-full mx-auto">
      <Button 
        className="w-full py-6 text-lg" 
        onClick={onAnalyze}
        disabled={isLoading}
      >
        <Sparkles className="w-5 h-5 mr-2" />
        {isLoading ? "Generating Analysis..." : "Generate AI Analysis"}
      </Button>

      {analysisResult && (
        <Card className="w-full mt-4">
          <CardHeader className="flex flex-row items-center justify-center pb-2">
            <CardTitle className="text-lg font-medium text-center">AI Analysis Results</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="whitespace-pre-wrap break-words">
              {formatAnalysisText(analysisResult)}
            </div>
            <Alert className="mb-4">
              <AlertDescription>
                Disclaimer: This analysis is generated by AI and may contain errors or inaccuracies. 
                Please use this information as one of many data points in your research process.
              </AlertDescription>
            </Alert>
            <Button 
              onClick={handleDownload}
              className="w-full gap-2 py-5 neo-brutal-shadow hover:bg-primary hover:text-primary-foreground transition-all duration-200"
              variant="outline"
            >
              <Download className="h-4 w-4" />
              Download Analysis as PDF
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
