
import { ArrowLeft, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { useToast } from "@/components/ui/use-toast";
import { generateAnalysisPDF } from "@/utils/pdfGenerator";

interface AIAnalysisDisplayProps {
  symbol: string;
  analysisResult: string;
  loading: boolean;
  onBack: () => void;
}

export function AIAnalysisDisplay({ 
  symbol, 
  analysisResult, 
  loading, 
  onBack 
}: AIAnalysisDisplayProps) {
  const { toast } = useToast();

  const formatAnalysisText = (text: string) => {
    return text.split('**').map((part, index) => 
      index % 2 === 1 ? <strong key={index} className="font-bold">{part}</strong> : part
    );
  };

  const downloadPDF = () => {
    try {
      const pdf = generateAnalysisPDF(symbol, analysisResult);
      pdf.save(`${symbol}_analysis.pdf`);

      toast({
        title: "Success",
        description: "Analysis report downloaded successfully",
      });
    } catch (error) {
      console.error("Error generating PDF:", error);
      toast({
        title: "Error",
        description: "Failed to generate PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="space-y-4 w-full max-w-7xl px-4">
      <Button variant="outline" onClick={onBack} className="mb-4">
        <ArrowLeft className="h-4 w-4 mr-2" />
        Back
      </Button>
      <div className="p-6 rounded-lg border bg-muted/50">
        <h3 className="font-semibold mb-4 text-xl">Analysis for {symbol}</h3>
        {loading ? (
          <div className="flex items-center justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        ) : (
          <>
            <div className="whitespace-pre-wrap break-words mb-6 text-lg leading-relaxed">
              {formatAnalysisText(analysisResult)}
            </div>
            <Alert className="mb-6">
              <AlertDescription>
                Disclaimer: This analysis is generated by AI and may contain errors or inaccuracies. 
                Please use this information as one of many data points in your research process.
              </AlertDescription>
            </Alert>
            <Button 
              onClick={downloadPDF}
              className="w-full gap-2 neo-brutal-shadow hover:bg-primary hover:text-primary-foreground transition-all duration-200"
              variant="outline"
            >
              <Download className="h-4 w-4" />
              Download Analysis as PDF
            </Button>
          </>
        )}
      </div>
    </div>
  );
}
